### ISSUE TITLE
linedb: method to tell when %fetch is done

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/linedb#13]
For example, if my app, `%foo`, needs to `%fetch` a repo from a remote ship and then do something with that repo, these operations must be sequential. Therefore my app `%foo` needs a way to tell when the `%fetch` is done. The way clay does this is by sending a `sign-arvo` after `%merg`. It might be nice to have a pokeback option in the `%fetch` poke, or a subscription path in `%linedb` that my app `%foo` can sub to to learn when the `%fetch` is done.

**Comment by hosted-fornet** [comment]
This is required for %ziggurat @tadad ; let me know if you prefer to take this issue or if I should.

**Comment by hosted-fornet** [comment]
https://github.com/uqbar-dao/linedb/issues/14#issuecomment-1523598176

Here you suggest using `+on-rock` to update when a repo/branch is updated. Will that not work for an initial creation of a sss as well? (I don't understand what rocks vs waves vs ... are, so maybe this is a very obvious thing).

**Comment by tadad** [comment]
this needs a refactor for when SSS actually comes out but for now this is solved
