### ISSUE TITLE
linedb: method to tell when a repo/branch has been updated

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/linedb#14]
For example, my app `%foo` wants to do something in response to new commits in a certain repo/branch. To make this possible, `%foo` must be able to somehow subscribe to `%linedb` so that when that repo/branch gets a new commit, `%foo` is informed.

This is possibly related to #13: you could imagine that exposing subscription paths to repos/branches that do not yet exist could be used to solve that issue as well as this one at the same time.

**Comment by hosted-fornet** [comment]
This is required for %ziggurat @tadad ; let me know if you prefer to take this issue or if I should.

**Comment by tadad** [comment]
I think this is going to be on-wave in sss eventually, I'll ask how to get this done now, it's definitely possible

**Comment by hosted-fornet** [comment]
Nice, thanks.

**Comment by tadad** [comment]
this is the `sss-on-rock` poke in linedb. Right now I have no logic in there so put whatever you need in there

**Comment by hosted-fornet** [comment]
Cool, thanks.

**Comment by tadad** [comment]
this needs a refactor for when SSS comes out for real with remote scry, works for now
