### ISSUE TITLE
State Corruption

### ISSUE THREAD

**Issue by tadad** [uqbar-dao/linedb#20]
To replicate:

1. commit & install %linedb
2. add some content to a repo/branch, e.g. `python3 scripts/linedb-load-files-from-directory.py test master ../blog/`
3. check queries working properly, e.g. `.^(* %gx /=linedb=/log/~nec/test/master/noun)`
4. make some trivial change to linedb (like adding a comment) and recommit
5. add more content to repo/branch, e.g. `python3 scripts/linedb-load-files-from-directory.py test master ../blog/`
6. running the same query as in 3 fails

**Comment by tadad** [comment]
I can no longer get this to replicate - not sure what happened?

**Comment by hosted-fornet** [comment]
Resolved in https://github.com/uqbar-dao/linedb/commit/10e29f098db9b04c278493b0374c04860cd51bf8
