### ISSUE TITLE
uqbuild: caching wrong

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/linedb#37]
We are doing caching wrong in uqbuild. Currently we hash based on the file's contents alone. But this means that if a dependency of the file changes, the file will not be recompiled as it should be the next time the file is built.

The most simple and obvious way might take too long(?) Specifically: change the hash to be on the contents of the file and all imports. OTOH, it is just map lookups, so it may be fast.

Let's take a closer look at clay's caching for inspiration, and also be thinking ourselves how to do this.

**Comment by tadad** [comment]
what if we just hashed the `pile:clay` instead of the text?

**Comment by hosted-fornet** [comment]
We should definitely dig into clay a bit if we can't think of an easy, fast, obvious solution.

**Comment by tadad** [comment]
resolved by #42
